# Site settings
title: Flylady Goes Binary
header-img: img/Theo.png
email: lesliemstevens@protonmail.com
copyright_name: flylady2
description: > # this means to ignore newlines until "baseurl:"
  From genetic code to computer code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  flylady2
learn_profile: flylady2
email_username: lesliemstevens@protonmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
